// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetJobResultsResultsJobIdGetData, GetJobResultsResultsJobIdGetErrors, GetJobResultsResultsJobIdGetResponses, GetJobStatusStatusJobIdGetData, GetJobStatusStatusJobIdGetErrors, GetJobStatusStatusJobIdGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, StartDetectionAnalysePostData, StartDetectionAnalysePostErrors, StartDetectionAnalysePostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Health check endpoint
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Analyse a video
 *
 * Start video analysis on a video
 */
export const startDetectionAnalysePost = <ThrowOnError extends boolean = false>(options: Options<StartDetectionAnalysePostData, ThrowOnError>) => (options.client ?? client).post<StartDetectionAnalysePostResponses, StartDetectionAnalysePostErrors, ThrowOnError>({
    security: [{ name: 'x-api-key', type: 'apiKey' }],
    url: '/analyse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the status of a detection job
 *
 * Get the status of a detection job
 */
export const getJobStatusStatusJobIdGet = <ThrowOnError extends boolean = false>(options: Options<GetJobStatusStatusJobIdGetData, ThrowOnError>) => (options.client ?? client).get<GetJobStatusStatusJobIdGetResponses, GetJobStatusStatusJobIdGetErrors, ThrowOnError>({ url: '/status/{job_id}', ...options });

/**
 * Get the results of a completed detection job
 */
export const getJobResultsResultsJobIdGet = <ThrowOnError extends boolean = false>(options: Options<GetJobResultsResultsJobIdGetData, ThrowOnError>) => (options.client ?? client).get<GetJobResultsResultsJobIdGetResponses, GetJobResultsResultsJobIdGetErrors, ThrowOnError>({ url: '/results/{job_id}', ...options });
