// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | (string & {});
};

export type Webhooks = JobCompletedjobCompletedPostWebhookRequest;

/**
 * BoundingBoxModel
 */
export type BoundingBoxModel = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

/**
 * CreateJobRequest
 */
export type CreateJobRequest = {
    job_type: JobType;
    /**
     * External Id
     *
     * Project identifier
     */
    external_id: string;
    /**
     * Video Url
     *
     * URL or path to video file
     */
    video_url: string;
    /**
     * Callback Url
     *
     * Callback URL for job completion notifications
     */
    callback_url?: string | null;
    /**
     * Params
     */
    params?: ObjectDetectParams | SceneDetectParams;
};

/**
 * CreateJobResponse
 */
export type CreateJobResponse = {
    /**
     * Job Id
     */
    job_id: string;
    job_type: JobType;
    /**
     * Status
     */
    status: string;
    /**
     * Queue Position
     */
    queue_position: number;
    /**
     * Message
     */
    message: string;
    /**
     * Callback Url
     */
    callback_url?: string | null;
};

/**
 * DetectionFrameModel
 */
export type DetectionFrameModel = {
    /**
     * Frame Idx
     */
    frame_idx: number;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Objects
     */
    objects: Array<DetectionObjectModel>;
};

/**
 * DetectionObjectModel
 */
export type DetectionObjectModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Class Name
     */
    class_name: string;
    /**
     * Confidence
     */
    confidence: number;
    bbox: BoundingBoxModel;
    /**
     * Thumbnail
     */
    thumbnail: string;
};

/**
 * DetectionResultsModel
 */
export type DetectionResultsModel = {
    /**
     * Result Type
     */
    result_type?: 'object_detect';
    /**
     * Version
     */
    version: string;
    metadata: ResultsMetadataModel;
    /**
     * Frames
     */
    frames: Array<DetectionFrameModel>;
};

/**
 * DetectionStatisticsModel
 */
export type DetectionStatisticsModel = {
    /**
     * Total Detections
     */
    total_detections?: number | null;
    /**
     * Person Detections
     */
    person_detections?: number | null;
    /**
     * Person With Face
     */
    person_with_face?: number | null;
    /**
     * Person Without Face
     */
    person_without_face?: number | null;
    /**
     * Other Detections
     */
    other_detections?: number | null;
    /**
     * Class Counts
     */
    class_counts?: {
        [key: string]: number;
    } | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Version
     */
    version: string;
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: string;
    job_stats?: JobStats | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * JobCompletedWebhook
 */
export type JobCompletedWebhook = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * External Id
     */
    external_id: string;
    /**
     * Job Type
     */
    job_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Timestamp
     */
    timestamp: Date;
};

/**
 * JobResultsResponse
 */
export type JobResultsResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Job Type
     */
    job_type?: string | null;
    /**
     * Data
     */
    data?: ({
        result_type: 'object_detect';
    } & DetectionResultsModel) | ({
        result_type: 'scene_detect';
    } & SceneDetectResultsModel) | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * JobStats
 */
export type JobStats = {
    /**
     * Queued
     */
    queued: number;
    /**
     * Processing
     */
    processing: number;
    /**
     * Completed
     */
    completed: number;
    /**
     * Failed
     */
    failed: number;
};

/**
 * JobStatusResponse
 */
export type JobStatusResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * External Id
     */
    external_id: string;
    /**
     * Job Type
     */
    job_type?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Queue Position
     */
    queue_position?: number;
    /**
     * Estimated Wait Time
     */
    estimated_wait_time?: string;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * JobType
 */
export const JobType = { OBJECT_DETECT: 'object_detect', SCENE_DETECT: 'scene_detect' } as const;

/**
 * JobType
 */
export type JobType = typeof JobType[keyof typeof JobType];

/**
 * ObjectDetectParams
 */
export type ObjectDetectParams = {
    /**
     * Similarity Threshold
     *
     * Similarity threshold for object tracking
     */
    similarity_threshold?: number;
    /**
     * Analysis Fps
     *
     * Frames per second to analyse (default 1)
     */
    analysis_fps?: number;
};

/**
 * ProcessingMetadataModel
 */
export type ProcessingMetadataModel = {
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Frames Processed
     */
    frames_processed?: number | null;
    /**
     * Frames With Detections
     */
    frames_with_detections?: number | null;
    /**
     * Processing Speed
     */
    processing_speed?: number | null;
    detection_statistics?: DetectionStatisticsModel | null;
};

/**
 * ResultsMetadataModel
 */
export type ResultsMetadataModel = {
    video: VideoMetadataModel;
    sprite: SpriteMetadataModel;
    processing: ProcessingMetadataModel;
};

/**
 * SceneDetectParams
 */
export type SceneDetectParams = {
    /**
     * Threshold
     *
     * Content detection sensitivity threshold
     */
    threshold?: number;
};

/**
 * SceneDetectResultsModel
 */
export type SceneDetectResultsModel = {
    /**
     * Result Type
     */
    result_type?: 'scene_detect';
    /**
     * Total Scenes
     */
    total_scenes: number;
    /**
     * Scenes
     */
    scenes: Array<SceneInfoModel>;
    /**
     * Sprite Url
     */
    sprite_url?: string | null;
    /**
     * Sprite Fragments
     */
    sprite_fragments?: Array<string> | null;
};

/**
 * SceneInfoModel
 */
export type SceneInfoModel = {
    /**
     * Scene Id
     */
    scene_id: number;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    /**
     * Start Seconds
     */
    start_seconds: number;
    /**
     * End Seconds
     */
    end_seconds: number;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
    /**
     * Sprite Fragment
     */
    sprite_fragment?: string | null;
};

/**
 * SpriteMetadataModel
 */
export type SpriteMetadataModel = {
    /**
     * Url
     */
    url: string;
    /**
     * Thumbnail Size
     */
    thumbnail_size: Array<number>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoMetadataModel
 */
export type VideoMetadataModel = {
    /**
     * Fps
     */
    fps: number;
    /**
     * Frame Count
     */
    frame_count: number;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Source
     */
    source: string;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type CreateJobData = {
    body: CreateJobRequest;
    path?: never;
    query?: never;
    url: '/job/create';
};

export type CreateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Successful Response
     */
    202: CreateJobResponse;
};

export type CreateJobResponse2 = CreateJobResponses[keyof CreateJobResponses];

export type GetJobStatusData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/status/{job_id}';
};

export type GetJobStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobStatusError = GetJobStatusErrors[keyof GetJobStatusErrors];

export type GetJobStatusResponses = {
    /**
     * Successful Response
     */
    200: JobStatusResponse;
};

export type GetJobStatusResponse = GetJobStatusResponses[keyof GetJobStatusResponses];

export type GetJobResultsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/job/{job_id}/results';
};

export type GetJobResultsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobResultsError = GetJobResultsErrors[keyof GetJobResultsErrors];

export type GetJobResultsResponses = {
    /**
     * Successful Response
     */
    200: JobResultsResponse;
};

export type GetJobResultsResponse = GetJobResultsResponses[keyof GetJobResultsResponses];

export type JobCompletedjobCompletedPostWebhookPayload = JobCompletedWebhook;

export type JobCompletedjobCompletedPostWebhookRequest = {
    body: JobCompletedjobCompletedPostWebhookPayload;
    key: 'job-completed';
    path?: never;
    query?: never;
};
